In [91]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn import metrics
from sklearn import preprocessing

In [92]:
df = pd.read_csv('connect-4.data',sep=",",header=None)
df

      0  1  2  3  4  5  6  7  8  9   ... 33 34 35 36 37 38 39 40 41    42
0      b  b  b  b  b  b  b  b  b  b  ...  b  b  b  b  b  b  b  b  b   win
1      b  b  b  b  b  b  b  b  b  b  ...  b  b  b  b  b  b  b  b  b   win
2      b  b  b  b  b  b  o  b  b  b  ...  b  b  b  b  b  b  b  b  b   win
3      b  b  b  b  b  b  b  b  b  b  ...  b  b  b  b  b  b  b  b  b   win
4      o  b  b  b  b  b  b  b  b  b  ...  b  b  b  b  b  b  b  b  b   win
...   .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. ..   ...
67552  x  x  b  b  b  b  o  x  o  b  ...  b  b  b  o  o  x  b  b  b  loss
67553  x  x  b  b  b  b  o  b  b  b  ...  b  b  b  o  x  o  o  x  b  draw
67554  x  x  b  b  b  b  o  o  b  b  ...  b  b  b  o  x  x  o  b  b  loss
67555  x  o  b  b  b  b  o  b  b  b  ...  b  b  b  o  x  o  x  x  b  draw
67556  x  o  o  o  x  b  o  b  b  b  ...  b  b  b  x  b  b  b  b  b  draw

[67557 rows x 43 columns]

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67557 entries, 0 to 67556
Data columns (total 43 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       67557 non-null  object
 1   1       67557 non-null  object
 2   2       67557 non-null  object
 3   3       67557 non-null  object
 4   4       67557 non-null  object
 5   5       67557 non-null  object
 6   6       67557 non-null  object
 7   7       67557 non-null  object
 8   8       67557 non-null  object
 9   9       67557 non-null  object
 10  10      67557 non-null  object
 11  11      67557 non-null  object
 12  12      67557 non-null  object
 13  13      67557 non-null  object
 14  14      67557 non-null  object
 15  15      67557 non-null  object
 16  16      67557 non-null  object
 17  17      67557 non-null  object
 18  18      67557 non-null  object
 19  19      67557 non-null  object
 20  20      67557 non-null  object
 21  21      67557 non-null  object
 22  22      67557 non-null  object
 23  23      67557 non-null  object
 24  24      67557 non-null  object
 25  25      67557 non-null  object
 26  26      67557 non-null  object
 27  27      67557 non-null  object
 28  28      67557 non-null  object
 29  29      67557 non-null  object
 30  30      67557 non-null  object
 31  31      67557 non-null  object
 32  32      67557 non-null  object
 33  33      67557 non-null  object
 34  34      67557 non-null  object
 35  35      67557 non-null  object
 36  36      67557 non-null  object
 37  37      67557 non-null  object
 38  38      67557 non-null  object
 39  39      67557 non-null  object
 40  40      67557 non-null  object
 41  41      67557 non-null  object
 42  42      67557 non-null  object
dtypes: object(43)
memory usage: 22.2+ MB

In [94]:
features = df.drop(42,axis=1)
labels = df[42]

In [95]:
features_onehot = pd.get_dummies(features,columns=features.columns)
features_onehot

,0_b,0_o,0_x,1_b,1_o,1_x,2_b,2_o,2_x,3_b,...,38_x,39_b,39_o,39_x,40_b,40_o,40_x,41_b,41_o,41_x
0,1,0,0,1,0,0,1,0,0,1,...,0,1,0,0,1,0,0,1,0,0
1,1,0,0,1,0,0,1,0,0,1,...,0,1,0,0,1,0,0,1,0,0
2,1,0,0,1,0,0,1,0,0,1,...,0,1,0,0,1,0,0,1,0,0
3,1,0,0,1,0,0,1,0,0,1,...,0,1,0,0,1,0,0,1,0,0
4,0,1,0,1,0,0,1,0,0,1,...,0,1,0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67552,0,0,1,0,0,1,1,0,0,1,...,1,1,0,0,1,0,0,1,0,0
67553,0,0,1,0,0,1,1,0,0,1,...,0,0,1,0,0,0,1,1,0,0
67554,0,0,1,0,0,1,1,0,0,1,...,1,0,1,0,1,0,0,1,0,0
67555,0,0,1,0,1,0,1,0,0,1,...,0,0,0,1,0,0,1,1,0,0
67556,0,0,1,0,1,0,0,1,0,0,...,0,1,0,0,1,0,0,1,0,0

In [96]:
def splitTrainTest(data,labels,size=0.4,random=42): 
    return train_test_split(data,labels,test_size=size,random_state=random)

In [97]:
feature_train, feature_test, label_train,label_test = splitTrainTest(features_onehot,labels,0.5,42)

In [107]:
feature_train.shape

(33778, 126)

In [99]:
classifier = tree.DecisionTreeClassifier(criterion='entropy',random_state=33)

In [100]:
classifier.fit(feature_train,label_train)

DecisionTreeClassifier(criterion='entropy', random_state=33)

In [101]:
tree_pred = classifier.predict(feature_test)

In [104]:
tree_score = metrics.accuracy_score(label_test,tree_pred)

In [105]:
print("Acc:",tree_score)
print("Report:", metrics.classification_report(label_test,tree_pred))

Acc: 0.7469433671807928
Report:               precision    recall  f1-score   support

        draw       0.26      0.27      0.27      3232
        loss       0.66      0.66      0.66      8332
         win       0.85      0.85      0.85     22215

    accuracy                           0.75     33779
   macro avg       0.59      0.59      0.59     33779
weighted avg       0.75      0.75      0.75     33779

In [106]:
tree_cm = metrics.confusion_matrix(label_test,tree_pred)

In [ ]:
import seaborn as sns
plt.figure(figsize=(12,12))
sns.heatmap(tree_cm,annot=True,fmt=".3f",linewidths=.5,square=True,cmap='Blues_r')
plt.